### PR TITLE
updating oauth-webapp for jax-rs 2.0. 

### PR DESCRIPTION
**Pull request by jadelkhoury**
updating oauth-webapp for jax-rs 2.0. 
replacing dependency on Wink with that on jax-rs2.0

### CODE REVIEW

**Comment by jadelkhoury** [comment]
I had no problems with this wink dependency when using Jetty. But it was very problematic when deploying an adaptor on Tomcat.

**Comment by berezovskyi** [comment]
Could you please fix the build config? I think we should remove JDK11 from the build matrix for now.

**Comment by berezovskyi** [comment]
Updated the build config.

@jadelkhoury you are free to merge if it builds well (both Travis checks pass).

**Comment by jadelkhoury** [comment]
Thanks @berezovskyi ! I wanted to try to fix the build myself, but just never got to it.

**Pull request merged**
